#!/bin/sh
# start and stop the web console server
cd webterm

case "$1" in
  start)
        node genconfig.js console.template console.json
        if [ -z "${DTCYBER}" ] ; then
            node ../../webterm/webterm-server -t console-server -p console.pid console.json >console.log 2>&1 &
        else
            node ${DTCYBER}/webterm/webterm-server -t console-server -p console.pid console.json >console.log 2>&1 &
        fi
	;;
  stop)
        kill `cat console.pid`
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
