#!/bin/sh
# start and stop the nosbeformatter process

curdir=$PWD
case "$1" in
  start)
        node lpt2pdf/nosbeformatter.js -p LP5xx_C12_E5 -s $curdir/printfiles  -o "-tof 3" > $curdir/pdf.log 2>&1  & 
	;;
  stop)
        kill `cat pdf.pid`
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
