#!/bin/sh
# start and stop the pdf printfile formatter process

curdir=$PWD
case "$1" in
  start)
        ./lpt2pdf/nosbeformatter.py --prtfile LP5xx_C12_E5 --pdfdir printfiles &
	;;
  stop)
        if [ -f pdf.pid ]; then
           kill `cat pdf.pid`
        fi
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
