#!/bin/sh
# start and stop the web terminal server
cd webterm

case "$1" in
  start)
        node genconfig.js config.template config.json
        if [ -z "${DTCYBER}" ] ; then
            node ../../webterm/webterm-server -p webterm.pid config.json >webterm.log 2>&1 &
        else
            node ${DTCYBER}/webterm/webterm-server -p webterm.pid config.json >webterm.log 2>&1 &
        fi
	;;
  stop)
        kill `cat webterm.pid`
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
